[project]
name = "QAT_pipeline"
channels = ["conda-forge"]          # keep for basics
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "3.11.*"
numpy = "*"
pandas = "*"
pytest = "*"
nltk = "*"

# Use PyPI for everything; Mac gets MPS, Linux gets CUDA via Docker env var
[pypi-dependencies]
torch = "*"
torchvision = "*"
torchaudio = "*"
transformers = "*"
datasets = "*"
einops = "*"
higher = "*"
hydra-core = "*"
wandb = "*"
jsonlines = "*"
sentencepiece = "*"
matplotlib = "*"
scikit-learn = "*"

[tasks]
test = "pytest -q"
