name: build-and-push
on:
  push: { branches: [main] }
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (linux/amd64)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/qat-pipeline:cu124-${{ github.sha }}
          docker buildx build --platform linux/amd64 -t $IMAGE --push .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Print image
        run: echo $IMAGE
